/**
 * Parity test between the TypeScript live calculator and the Python engine.
 *
 * Golden file is generated by the Python script in
 * costaplanner/skills/costa-rica-structural/python_port/tests/fixtures/
 * flexure_steps_golden.json. It's a snapshot of `design_flexure(...)` +
 * `build_flexure_steps(...)` output for 24 representative beam inputs
 * (random spread + canonical fixtures + doubly-reinforcement edge case).
 *
 * Each case is run through the TS port and every numeric output is asserted
 * against the Python truth value within 1e-9 relative tolerance. If math
 * drifts, this test fails the build before deployment.
 */
import { describe, it, expect } from "vitest";
import golden from "./__fixtures__/flexure_steps_golden.json";
import {
  computeBeamFlexureLive,
  buildFlexureSteps,
  type FlexureInput,
  type FlexureLiveResult,
} from "./beam-flexure-live";

interface GoldenCase {
  input: FlexureInput;
  result: {
    [key: string]: number | boolean;
  };
  steps: Array<{
    id: string;
    output_value: number;
    output_var: string;
  }>;
}

const TOL = 1e-9;

function rel(a: number, b: number): number {
  const denom = Math.max(Math.abs(a), Math.abs(b), 1);
  return Math.abs(a - b) / denom;
}

describe("beam-flexure-live parity with Python", () => {
  const cases = golden as unknown as GoldenCase[];

  it("loaded golden file has cases", () => {
    expect(cases.length).toBeGreaterThanOrEqual(20);
  });

  cases.forEach((c, i) => {
    const tag = `case ${i + 1}: b=${c.input.b} h=${c.input.h} Mu=${c.input.Mu_tonm} fc=${c.input.fc}`;

    it(`scalar fields match — ${tag}`, () => {
      const r = computeBeamFlexureLive(c.input);
      const numericFields: Array<keyof FlexureLiveResult> = [
        "Mu_kgcm", "phi", "phi_bd2", "Rn", "m",
        "arg", "one_minus_arg", "sqrt_term",
        "rho_req", "As_req",
        "As_min_flex_1", "As_min_flex_2", "As_min_flex", "As_min_temp",
        "As_diseno",
        "rho_diseno", "rho_max_val", "beta1",
        "c_na",
      ];
      for (const f of numericFields) {
        const got = r[f] as number;
        const want = c.result[f] as number;
        expect(rel(got, want), `${f}: ts=${got}, py=${want}`).toBeLessThan(TOL);
      }
      // boolean flags must match
      expect(r.tension_controlled).toBe(c.result.tension_controlled);
      expect(r.requires_doubly).toBe(c.result.requires_doubly);
    });

    it(`eps_s matches (handling inf as 1.0) — ${tag}`, () => {
      const r = computeBeamFlexureLive(c.input);
      const tsEps = Number.isFinite(r.eps_s) ? r.eps_s : 1.0;
      const pyEps = c.result.eps_s as number;
      expect(rel(tsEps, pyEps), `eps_s: ts=${tsEps}, py=${pyEps}`).toBeLessThan(TOL);
    });

    it(`step list matches Python — ${tag}`, () => {
      const r = computeBeamFlexureLive(c.input);
      const tsSteps = buildFlexureSteps(r);
      expect(tsSteps.length).toBe(c.steps.length);
      for (let k = 0; k < tsSteps.length; k++) {
        const ts = tsSteps[k];
        const py = c.steps[k];
        expect(ts.id).toBe(py.id);
        expect(ts.output_var).toBe(py.output_var);
        expect(rel(ts.output_value, py.output_value), `step ${py.id}: ts=${ts.output_value}, py=${py.output_value}`).toBeLessThan(TOL);
      }
    });
  });
});
